// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/apikeyroutefailovertarget"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// APIKeyRouteFailoverTargetUpdate is the builder for updating APIKeyRouteFailoverTarget entities.
type APIKeyRouteFailoverTargetUpdate struct {
	config
	hooks    []Hook
	mutation *APIKeyRouteFailoverTargetMutation
}

// Where appends a list predicates to the APIKeyRouteFailoverTargetUpdate builder.
func (_u *APIKeyRouteFailoverTargetUpdate) Where(ps ...predicate.APIKeyRouteFailoverTarget) *APIKeyRouteFailoverTargetUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *APIKeyRouteFailoverTargetUpdate) SetUpdatedAt(v time.Time) *APIKeyRouteFailoverTargetUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *APIKeyRouteFailoverTargetUpdate) SetAPIKeyID(v int64) *APIKeyRouteFailoverTargetUpdate {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *APIKeyRouteFailoverTargetUpdate) SetNillableAPIKeyID(v *int64) *APIKeyRouteFailoverTargetUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetTargetGroupID sets the "target_group_id" field.
func (_u *APIKeyRouteFailoverTargetUpdate) SetTargetGroupID(v int64) *APIKeyRouteFailoverTargetUpdate {
	_u.mutation.SetTargetGroupID(v)
	return _u
}

// SetNillableTargetGroupID sets the "target_group_id" field if the given value is not nil.
func (_u *APIKeyRouteFailoverTargetUpdate) SetNillableTargetGroupID(v *int64) *APIKeyRouteFailoverTargetUpdate {
	if v != nil {
		_u.SetTargetGroupID(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *APIKeyRouteFailoverTargetUpdate) SetPriority(v int) *APIKeyRouteFailoverTargetUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *APIKeyRouteFailoverTargetUpdate) SetNillablePriority(v *int) *APIKeyRouteFailoverTargetUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *APIKeyRouteFailoverTargetUpdate) AddPriority(v int) *APIKeyRouteFailoverTargetUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *APIKeyRouteFailoverTargetUpdate) SetAPIKey(v *APIKey) *APIKeyRouteFailoverTargetUpdate {
	return _u.SetAPIKeyID(v.ID)
}

// SetTargetGroup sets the "target_group" edge to the Group entity.
func (_u *APIKeyRouteFailoverTargetUpdate) SetTargetGroup(v *Group) *APIKeyRouteFailoverTargetUpdate {
	return _u.SetTargetGroupID(v.ID)
}

// Mutation returns the APIKeyRouteFailoverTargetMutation object of the builder.
func (_u *APIKeyRouteFailoverTargetUpdate) Mutation() *APIKeyRouteFailoverTargetMutation {
	return _u.mutation
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *APIKeyRouteFailoverTargetUpdate) ClearAPIKey() *APIKeyRouteFailoverTargetUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// ClearTargetGroup clears the "target_group" edge to the Group entity.
func (_u *APIKeyRouteFailoverTargetUpdate) ClearTargetGroup() *APIKeyRouteFailoverTargetUpdate {
	_u.mutation.ClearTargetGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *APIKeyRouteFailoverTargetUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeyRouteFailoverTargetUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *APIKeyRouteFailoverTargetUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeyRouteFailoverTargetUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIKeyRouteFailoverTargetUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := apikeyroutefailovertarget.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIKeyRouteFailoverTargetUpdate) check() error {
	if v, ok := _u.mutation.Priority(); ok {
		if err := apikeyroutefailovertarget.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "APIKeyRouteFailoverTarget.priority": %w`, err)}
		}
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyRouteFailoverTarget.api_key"`)
	}
	if _u.mutation.TargetGroupCleared() && len(_u.mutation.TargetGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyRouteFailoverTarget.target_group"`)
	}
	return nil
}

func (_u *APIKeyRouteFailoverTargetUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikeyroutefailovertarget.Table, apikeyroutefailovertarget.Columns, sqlgraph.NewFieldSpec(apikeyroutefailovertarget.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeyroutefailovertarget.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(apikeyroutefailovertarget.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(apikeyroutefailovertarget.FieldPriority, field.TypeInt, value)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeyroutefailovertarget.APIKeyTable,
			Columns: []string{apikeyroutefailovertarget.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeyroutefailovertarget.APIKeyTable,
			Columns: []string{apikeyroutefailovertarget.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TargetGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   apikeyroutefailovertarget.TargetGroupTable,
			Columns: []string{apikeyroutefailovertarget.TargetGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   apikeyroutefailovertarget.TargetGroupTable,
			Columns: []string{apikeyroutefailovertarget.TargetGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikeyroutefailovertarget.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// APIKeyRouteFailoverTargetUpdateOne is the builder for updating a single APIKeyRouteFailoverTarget entity.
type APIKeyRouteFailoverTargetUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *APIKeyRouteFailoverTargetMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *APIKeyRouteFailoverTargetUpdateOne) SetUpdatedAt(v time.Time) *APIKeyRouteFailoverTargetUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *APIKeyRouteFailoverTargetUpdateOne) SetAPIKeyID(v int64) *APIKeyRouteFailoverTargetUpdateOne {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *APIKeyRouteFailoverTargetUpdateOne) SetNillableAPIKeyID(v *int64) *APIKeyRouteFailoverTargetUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetTargetGroupID sets the "target_group_id" field.
func (_u *APIKeyRouteFailoverTargetUpdateOne) SetTargetGroupID(v int64) *APIKeyRouteFailoverTargetUpdateOne {
	_u.mutation.SetTargetGroupID(v)
	return _u
}

// SetNillableTargetGroupID sets the "target_group_id" field if the given value is not nil.
func (_u *APIKeyRouteFailoverTargetUpdateOne) SetNillableTargetGroupID(v *int64) *APIKeyRouteFailoverTargetUpdateOne {
	if v != nil {
		_u.SetTargetGroupID(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *APIKeyRouteFailoverTargetUpdateOne) SetPriority(v int) *APIKeyRouteFailoverTargetUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *APIKeyRouteFailoverTargetUpdateOne) SetNillablePriority(v *int) *APIKeyRouteFailoverTargetUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *APIKeyRouteFailoverTargetUpdateOne) AddPriority(v int) *APIKeyRouteFailoverTargetUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *APIKeyRouteFailoverTargetUpdateOne) SetAPIKey(v *APIKey) *APIKeyRouteFailoverTargetUpdateOne {
	return _u.SetAPIKeyID(v.ID)
}

// SetTargetGroup sets the "target_group" edge to the Group entity.
func (_u *APIKeyRouteFailoverTargetUpdateOne) SetTargetGroup(v *Group) *APIKeyRouteFailoverTargetUpdateOne {
	return _u.SetTargetGroupID(v.ID)
}

// Mutation returns the APIKeyRouteFailoverTargetMutation object of the builder.
func (_u *APIKeyRouteFailoverTargetUpdateOne) Mutation() *APIKeyRouteFailoverTargetMutation {
	return _u.mutation
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *APIKeyRouteFailoverTargetUpdateOne) ClearAPIKey() *APIKeyRouteFailoverTargetUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// ClearTargetGroup clears the "target_group" edge to the Group entity.
func (_u *APIKeyRouteFailoverTargetUpdateOne) ClearTargetGroup() *APIKeyRouteFailoverTargetUpdateOne {
	_u.mutation.ClearTargetGroup()
	return _u
}

// Where appends a list predicates to the APIKeyRouteFailoverTargetUpdate builder.
func (_u *APIKeyRouteFailoverTargetUpdateOne) Where(ps ...predicate.APIKeyRouteFailoverTarget) *APIKeyRouteFailoverTargetUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *APIKeyRouteFailoverTargetUpdateOne) Select(field string, fields ...string) *APIKeyRouteFailoverTargetUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated APIKeyRouteFailoverTarget entity.
func (_u *APIKeyRouteFailoverTargetUpdateOne) Save(ctx context.Context) (*APIKeyRouteFailoverTarget, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *APIKeyRouteFailoverTargetUpdateOne) SaveX(ctx context.Context) *APIKeyRouteFailoverTarget {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *APIKeyRouteFailoverTargetUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *APIKeyRouteFailoverTargetUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *APIKeyRouteFailoverTargetUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := apikeyroutefailovertarget.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *APIKeyRouteFailoverTargetUpdateOne) check() error {
	if v, ok := _u.mutation.Priority(); ok {
		if err := apikeyroutefailovertarget.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "APIKeyRouteFailoverTarget.priority": %w`, err)}
		}
	}
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyRouteFailoverTarget.api_key"`)
	}
	if _u.mutation.TargetGroupCleared() && len(_u.mutation.TargetGroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "APIKeyRouteFailoverTarget.target_group"`)
	}
	return nil
}

func (_u *APIKeyRouteFailoverTargetUpdateOne) sqlSave(ctx context.Context) (_node *APIKeyRouteFailoverTarget, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikeyroutefailovertarget.Table, apikeyroutefailovertarget.Columns, sqlgraph.NewFieldSpec(apikeyroutefailovertarget.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "APIKeyRouteFailoverTarget.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apikeyroutefailovertarget.FieldID)
		for _, f := range fields {
			if !apikeyroutefailovertarget.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apikeyroutefailovertarget.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeyroutefailovertarget.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(apikeyroutefailovertarget.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(apikeyroutefailovertarget.FieldPriority, field.TypeInt, value)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeyroutefailovertarget.APIKeyTable,
			Columns: []string{apikeyroutefailovertarget.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeyroutefailovertarget.APIKeyTable,
			Columns: []string{apikeyroutefailovertarget.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TargetGroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   apikeyroutefailovertarget.TargetGroupTable,
			Columns: []string{apikeyroutefailovertarget.TargetGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TargetGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   apikeyroutefailovertarget.TargetGroupTable,
			Columns: []string{apikeyroutefailovertarget.TargetGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &APIKeyRouteFailoverTarget{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikeyroutefailovertarget.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
