// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/apikeyroutefailovertarget"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// APIKeyRouteFailoverTargetCreate is the builder for creating a APIKeyRouteFailoverTarget entity.
type APIKeyRouteFailoverTargetCreate struct {
	config
	mutation *APIKeyRouteFailoverTargetMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *APIKeyRouteFailoverTargetCreate) SetCreatedAt(v time.Time) *APIKeyRouteFailoverTargetCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *APIKeyRouteFailoverTargetCreate) SetNillableCreatedAt(v *time.Time) *APIKeyRouteFailoverTargetCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *APIKeyRouteFailoverTargetCreate) SetUpdatedAt(v time.Time) *APIKeyRouteFailoverTargetCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *APIKeyRouteFailoverTargetCreate) SetNillableUpdatedAt(v *time.Time) *APIKeyRouteFailoverTargetCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *APIKeyRouteFailoverTargetCreate) SetAPIKeyID(v int64) *APIKeyRouteFailoverTargetCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetTargetGroupID sets the "target_group_id" field.
func (_c *APIKeyRouteFailoverTargetCreate) SetTargetGroupID(v int64) *APIKeyRouteFailoverTargetCreate {
	_c.mutation.SetTargetGroupID(v)
	return _c
}

// SetPriority sets the "priority" field.
func (_c *APIKeyRouteFailoverTargetCreate) SetPriority(v int) *APIKeyRouteFailoverTargetCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_c *APIKeyRouteFailoverTargetCreate) SetAPIKey(v *APIKey) *APIKeyRouteFailoverTargetCreate {
	return _c.SetAPIKeyID(v.ID)
}

// SetTargetGroup sets the "target_group" edge to the Group entity.
func (_c *APIKeyRouteFailoverTargetCreate) SetTargetGroup(v *Group) *APIKeyRouteFailoverTargetCreate {
	return _c.SetTargetGroupID(v.ID)
}

// Mutation returns the APIKeyRouteFailoverTargetMutation object of the builder.
func (_c *APIKeyRouteFailoverTargetCreate) Mutation() *APIKeyRouteFailoverTargetMutation {
	return _c.mutation
}

// Save creates the APIKeyRouteFailoverTarget in the database.
func (_c *APIKeyRouteFailoverTargetCreate) Save(ctx context.Context) (*APIKeyRouteFailoverTarget, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *APIKeyRouteFailoverTargetCreate) SaveX(ctx context.Context) *APIKeyRouteFailoverTarget {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIKeyRouteFailoverTargetCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIKeyRouteFailoverTargetCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *APIKeyRouteFailoverTargetCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := apikeyroutefailovertarget.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := apikeyroutefailovertarget.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *APIKeyRouteFailoverTargetCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "APIKeyRouteFailoverTarget.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "APIKeyRouteFailoverTarget.updated_at"`)}
	}
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "APIKeyRouteFailoverTarget.api_key_id"`)}
	}
	if _, ok := _c.mutation.TargetGroupID(); !ok {
		return &ValidationError{Name: "target_group_id", err: errors.New(`ent: missing required field "APIKeyRouteFailoverTarget.target_group_id"`)}
	}
	if _, ok := _c.mutation.Priority(); !ok {
		return &ValidationError{Name: "priority", err: errors.New(`ent: missing required field "APIKeyRouteFailoverTarget.priority"`)}
	}
	if v, ok := _c.mutation.Priority(); ok {
		if err := apikeyroutefailovertarget.PriorityValidator(v); err != nil {
			return &ValidationError{Name: "priority", err: fmt.Errorf(`ent: validator failed for field "APIKeyRouteFailoverTarget.priority": %w`, err)}
		}
	}
	if len(_c.mutation.APIKeyIDs()) == 0 {
		return &ValidationError{Name: "api_key", err: errors.New(`ent: missing required edge "APIKeyRouteFailoverTarget.api_key"`)}
	}
	if len(_c.mutation.TargetGroupIDs()) == 0 {
		return &ValidationError{Name: "target_group", err: errors.New(`ent: missing required edge "APIKeyRouteFailoverTarget.target_group"`)}
	}
	return nil
}

func (_c *APIKeyRouteFailoverTargetCreate) sqlSave(ctx context.Context) (*APIKeyRouteFailoverTarget, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *APIKeyRouteFailoverTargetCreate) createSpec() (*APIKeyRouteFailoverTarget, *sqlgraph.CreateSpec) {
	var (
		_node = &APIKeyRouteFailoverTarget{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(apikeyroutefailovertarget.Table, sqlgraph.NewFieldSpec(apikeyroutefailovertarget.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(apikeyroutefailovertarget.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeyroutefailovertarget.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(apikeyroutefailovertarget.FieldPriority, field.TypeInt, value)
		_node.Priority = value
	}
	if nodes := _c.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeyroutefailovertarget.APIKeyTable,
			Columns: []string{apikeyroutefailovertarget.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.APIKeyID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TargetGroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   apikeyroutefailovertarget.TargetGroupTable,
			Columns: []string{apikeyroutefailovertarget.TargetGroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TargetGroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIKeyRouteFailoverTarget.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APIKeyRouteFailoverTargetUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *APIKeyRouteFailoverTargetCreate) OnConflict(opts ...sql.ConflictOption) *APIKeyRouteFailoverTargetUpsertOne {
	_c.conflict = opts
	return &APIKeyRouteFailoverTargetUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIKeyRouteFailoverTarget.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APIKeyRouteFailoverTargetCreate) OnConflictColumns(columns ...string) *APIKeyRouteFailoverTargetUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APIKeyRouteFailoverTargetUpsertOne{
		create: _c,
	}
}

type (
	// APIKeyRouteFailoverTargetUpsertOne is the builder for "upsert"-ing
	//  one APIKeyRouteFailoverTarget node.
	APIKeyRouteFailoverTargetUpsertOne struct {
		create *APIKeyRouteFailoverTargetCreate
	}

	// APIKeyRouteFailoverTargetUpsert is the "OnConflict" setter.
	APIKeyRouteFailoverTargetUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyRouteFailoverTargetUpsert) SetUpdatedAt(v time.Time) *APIKeyRouteFailoverTargetUpsert {
	u.Set(apikeyroutefailovertarget.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyRouteFailoverTargetUpsert) UpdateUpdatedAt() *APIKeyRouteFailoverTargetUpsert {
	u.SetExcluded(apikeyroutefailovertarget.FieldUpdatedAt)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *APIKeyRouteFailoverTargetUpsert) SetAPIKeyID(v int64) *APIKeyRouteFailoverTargetUpsert {
	u.Set(apikeyroutefailovertarget.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *APIKeyRouteFailoverTargetUpsert) UpdateAPIKeyID() *APIKeyRouteFailoverTargetUpsert {
	u.SetExcluded(apikeyroutefailovertarget.FieldAPIKeyID)
	return u
}

// SetTargetGroupID sets the "target_group_id" field.
func (u *APIKeyRouteFailoverTargetUpsert) SetTargetGroupID(v int64) *APIKeyRouteFailoverTargetUpsert {
	u.Set(apikeyroutefailovertarget.FieldTargetGroupID, v)
	return u
}

// UpdateTargetGroupID sets the "target_group_id" field to the value that was provided on create.
func (u *APIKeyRouteFailoverTargetUpsert) UpdateTargetGroupID() *APIKeyRouteFailoverTargetUpsert {
	u.SetExcluded(apikeyroutefailovertarget.FieldTargetGroupID)
	return u
}

// SetPriority sets the "priority" field.
func (u *APIKeyRouteFailoverTargetUpsert) SetPriority(v int) *APIKeyRouteFailoverTargetUpsert {
	u.Set(apikeyroutefailovertarget.FieldPriority, v)
	return u
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *APIKeyRouteFailoverTargetUpsert) UpdatePriority() *APIKeyRouteFailoverTargetUpsert {
	u.SetExcluded(apikeyroutefailovertarget.FieldPriority)
	return u
}

// AddPriority adds v to the "priority" field.
func (u *APIKeyRouteFailoverTargetUpsert) AddPriority(v int) *APIKeyRouteFailoverTargetUpsert {
	u.Add(apikeyroutefailovertarget.FieldPriority, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.APIKeyRouteFailoverTarget.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *APIKeyRouteFailoverTargetUpsertOne) UpdateNewValues() *APIKeyRouteFailoverTargetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(apikeyroutefailovertarget.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIKeyRouteFailoverTarget.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *APIKeyRouteFailoverTargetUpsertOne) Ignore() *APIKeyRouteFailoverTargetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APIKeyRouteFailoverTargetUpsertOne) DoNothing() *APIKeyRouteFailoverTargetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APIKeyRouteFailoverTargetCreate.OnConflict
// documentation for more info.
func (u *APIKeyRouteFailoverTargetUpsertOne) Update(set func(*APIKeyRouteFailoverTargetUpsert)) *APIKeyRouteFailoverTargetUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APIKeyRouteFailoverTargetUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyRouteFailoverTargetUpsertOne) SetUpdatedAt(v time.Time) *APIKeyRouteFailoverTargetUpsertOne {
	return u.Update(func(s *APIKeyRouteFailoverTargetUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyRouteFailoverTargetUpsertOne) UpdateUpdatedAt() *APIKeyRouteFailoverTargetUpsertOne {
	return u.Update(func(s *APIKeyRouteFailoverTargetUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *APIKeyRouteFailoverTargetUpsertOne) SetAPIKeyID(v int64) *APIKeyRouteFailoverTargetUpsertOne {
	return u.Update(func(s *APIKeyRouteFailoverTargetUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *APIKeyRouteFailoverTargetUpsertOne) UpdateAPIKeyID() *APIKeyRouteFailoverTargetUpsertOne {
	return u.Update(func(s *APIKeyRouteFailoverTargetUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetTargetGroupID sets the "target_group_id" field.
func (u *APIKeyRouteFailoverTargetUpsertOne) SetTargetGroupID(v int64) *APIKeyRouteFailoverTargetUpsertOne {
	return u.Update(func(s *APIKeyRouteFailoverTargetUpsert) {
		s.SetTargetGroupID(v)
	})
}

// UpdateTargetGroupID sets the "target_group_id" field to the value that was provided on create.
func (u *APIKeyRouteFailoverTargetUpsertOne) UpdateTargetGroupID() *APIKeyRouteFailoverTargetUpsertOne {
	return u.Update(func(s *APIKeyRouteFailoverTargetUpsert) {
		s.UpdateTargetGroupID()
	})
}

// SetPriority sets the "priority" field.
func (u *APIKeyRouteFailoverTargetUpsertOne) SetPriority(v int) *APIKeyRouteFailoverTargetUpsertOne {
	return u.Update(func(s *APIKeyRouteFailoverTargetUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *APIKeyRouteFailoverTargetUpsertOne) AddPriority(v int) *APIKeyRouteFailoverTargetUpsertOne {
	return u.Update(func(s *APIKeyRouteFailoverTargetUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *APIKeyRouteFailoverTargetUpsertOne) UpdatePriority() *APIKeyRouteFailoverTargetUpsertOne {
	return u.Update(func(s *APIKeyRouteFailoverTargetUpsert) {
		s.UpdatePriority()
	})
}

// Exec executes the query.
func (u *APIKeyRouteFailoverTargetUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for APIKeyRouteFailoverTargetCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APIKeyRouteFailoverTargetUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *APIKeyRouteFailoverTargetUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *APIKeyRouteFailoverTargetUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// APIKeyRouteFailoverTargetCreateBulk is the builder for creating many APIKeyRouteFailoverTarget entities in bulk.
type APIKeyRouteFailoverTargetCreateBulk struct {
	config
	err      error
	builders []*APIKeyRouteFailoverTargetCreate
	conflict []sql.ConflictOption
}

// Save creates the APIKeyRouteFailoverTarget entities in the database.
func (_c *APIKeyRouteFailoverTargetCreateBulk) Save(ctx context.Context) ([]*APIKeyRouteFailoverTarget, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*APIKeyRouteFailoverTarget, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*APIKeyRouteFailoverTargetMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *APIKeyRouteFailoverTargetCreateBulk) SaveX(ctx context.Context) []*APIKeyRouteFailoverTarget {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *APIKeyRouteFailoverTargetCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *APIKeyRouteFailoverTargetCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.APIKeyRouteFailoverTarget.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.APIKeyRouteFailoverTargetUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *APIKeyRouteFailoverTargetCreateBulk) OnConflict(opts ...sql.ConflictOption) *APIKeyRouteFailoverTargetUpsertBulk {
	_c.conflict = opts
	return &APIKeyRouteFailoverTargetUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.APIKeyRouteFailoverTarget.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *APIKeyRouteFailoverTargetCreateBulk) OnConflictColumns(columns ...string) *APIKeyRouteFailoverTargetUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &APIKeyRouteFailoverTargetUpsertBulk{
		create: _c,
	}
}

// APIKeyRouteFailoverTargetUpsertBulk is the builder for "upsert"-ing
// a bulk of APIKeyRouteFailoverTarget nodes.
type APIKeyRouteFailoverTargetUpsertBulk struct {
	create *APIKeyRouteFailoverTargetCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.APIKeyRouteFailoverTarget.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *APIKeyRouteFailoverTargetUpsertBulk) UpdateNewValues() *APIKeyRouteFailoverTargetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(apikeyroutefailovertarget.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.APIKeyRouteFailoverTarget.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *APIKeyRouteFailoverTargetUpsertBulk) Ignore() *APIKeyRouteFailoverTargetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *APIKeyRouteFailoverTargetUpsertBulk) DoNothing() *APIKeyRouteFailoverTargetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the APIKeyRouteFailoverTargetCreateBulk.OnConflict
// documentation for more info.
func (u *APIKeyRouteFailoverTargetUpsertBulk) Update(set func(*APIKeyRouteFailoverTargetUpsert)) *APIKeyRouteFailoverTargetUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&APIKeyRouteFailoverTargetUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *APIKeyRouteFailoverTargetUpsertBulk) SetUpdatedAt(v time.Time) *APIKeyRouteFailoverTargetUpsertBulk {
	return u.Update(func(s *APIKeyRouteFailoverTargetUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *APIKeyRouteFailoverTargetUpsertBulk) UpdateUpdatedAt() *APIKeyRouteFailoverTargetUpsertBulk {
	return u.Update(func(s *APIKeyRouteFailoverTargetUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *APIKeyRouteFailoverTargetUpsertBulk) SetAPIKeyID(v int64) *APIKeyRouteFailoverTargetUpsertBulk {
	return u.Update(func(s *APIKeyRouteFailoverTargetUpsert) {
		s.SetAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *APIKeyRouteFailoverTargetUpsertBulk) UpdateAPIKeyID() *APIKeyRouteFailoverTargetUpsertBulk {
	return u.Update(func(s *APIKeyRouteFailoverTargetUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetTargetGroupID sets the "target_group_id" field.
func (u *APIKeyRouteFailoverTargetUpsertBulk) SetTargetGroupID(v int64) *APIKeyRouteFailoverTargetUpsertBulk {
	return u.Update(func(s *APIKeyRouteFailoverTargetUpsert) {
		s.SetTargetGroupID(v)
	})
}

// UpdateTargetGroupID sets the "target_group_id" field to the value that was provided on create.
func (u *APIKeyRouteFailoverTargetUpsertBulk) UpdateTargetGroupID() *APIKeyRouteFailoverTargetUpsertBulk {
	return u.Update(func(s *APIKeyRouteFailoverTargetUpsert) {
		s.UpdateTargetGroupID()
	})
}

// SetPriority sets the "priority" field.
func (u *APIKeyRouteFailoverTargetUpsertBulk) SetPriority(v int) *APIKeyRouteFailoverTargetUpsertBulk {
	return u.Update(func(s *APIKeyRouteFailoverTargetUpsert) {
		s.SetPriority(v)
	})
}

// AddPriority adds v to the "priority" field.
func (u *APIKeyRouteFailoverTargetUpsertBulk) AddPriority(v int) *APIKeyRouteFailoverTargetUpsertBulk {
	return u.Update(func(s *APIKeyRouteFailoverTargetUpsert) {
		s.AddPriority(v)
	})
}

// UpdatePriority sets the "priority" field to the value that was provided on create.
func (u *APIKeyRouteFailoverTargetUpsertBulk) UpdatePriority() *APIKeyRouteFailoverTargetUpsertBulk {
	return u.Update(func(s *APIKeyRouteFailoverTargetUpsert) {
		s.UpdatePriority()
	})
}

// Exec executes the query.
func (u *APIKeyRouteFailoverTargetUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the APIKeyRouteFailoverTargetCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for APIKeyRouteFailoverTargetCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *APIKeyRouteFailoverTargetUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
