// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/apikeyroutefailovertarget"
	"github.com/Wei-Shaw/sub2api/ent/group"
)

// APIKeyRouteFailoverTarget is the model entity for the APIKeyRouteFailoverTarget schema.
type APIKeyRouteFailoverTarget struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// TargetGroupID holds the value of the "target_group_id" field.
	TargetGroupID int64 `json:"target_group_id,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority int `json:"priority,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the APIKeyRouteFailoverTargetQuery when eager-loading is set.
	Edges        APIKeyRouteFailoverTargetEdges `json:"edges"`
	selectValues sql.SelectValues
}

// APIKeyRouteFailoverTargetEdges holds the relations/edges for other nodes in the graph.
type APIKeyRouteFailoverTargetEdges struct {
	// APIKey holds the value of the api_key edge.
	APIKey *APIKey `json:"api_key,omitempty"`
	// TargetGroup holds the value of the target_group edge.
	TargetGroup *Group `json:"target_group,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// APIKeyOrErr returns the APIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e APIKeyRouteFailoverTargetEdges) APIKeyOrErr() (*APIKey, error) {
	if e.APIKey != nil {
		return e.APIKey, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "api_key"}
}

// TargetGroupOrErr returns the TargetGroup value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e APIKeyRouteFailoverTargetEdges) TargetGroupOrErr() (*Group, error) {
	if e.TargetGroup != nil {
		return e.TargetGroup, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: group.Label}
	}
	return nil, &NotLoadedError{edge: "target_group"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*APIKeyRouteFailoverTarget) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case apikeyroutefailovertarget.FieldID, apikeyroutefailovertarget.FieldAPIKeyID, apikeyroutefailovertarget.FieldTargetGroupID, apikeyroutefailovertarget.FieldPriority:
			values[i] = new(sql.NullInt64)
		case apikeyroutefailovertarget.FieldCreatedAt, apikeyroutefailovertarget.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the APIKeyRouteFailoverTarget fields.
func (_m *APIKeyRouteFailoverTarget) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case apikeyroutefailovertarget.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case apikeyroutefailovertarget.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case apikeyroutefailovertarget.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case apikeyroutefailovertarget.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case apikeyroutefailovertarget.FieldTargetGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field target_group_id", values[i])
			} else if value.Valid {
				_m.TargetGroupID = value.Int64
			}
		case apikeyroutefailovertarget.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the APIKeyRouteFailoverTarget.
// This includes values selected through modifiers, order, etc.
func (_m *APIKeyRouteFailoverTarget) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAPIKey queries the "api_key" edge of the APIKeyRouteFailoverTarget entity.
func (_m *APIKeyRouteFailoverTarget) QueryAPIKey() *APIKeyQuery {
	return NewAPIKeyRouteFailoverTargetClient(_m.config).QueryAPIKey(_m)
}

// QueryTargetGroup queries the "target_group" edge of the APIKeyRouteFailoverTarget entity.
func (_m *APIKeyRouteFailoverTarget) QueryTargetGroup() *GroupQuery {
	return NewAPIKeyRouteFailoverTargetClient(_m.config).QueryTargetGroup(_m)
}

// Update returns a builder for updating this APIKeyRouteFailoverTarget.
// Note that you need to call APIKeyRouteFailoverTarget.Unwrap() before calling this method if this APIKeyRouteFailoverTarget
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *APIKeyRouteFailoverTarget) Update() *APIKeyRouteFailoverTargetUpdateOne {
	return NewAPIKeyRouteFailoverTargetClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the APIKeyRouteFailoverTarget entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *APIKeyRouteFailoverTarget) Unwrap() *APIKeyRouteFailoverTarget {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: APIKeyRouteFailoverTarget is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *APIKeyRouteFailoverTarget) String() string {
	var builder strings.Builder
	builder.WriteString("APIKeyRouteFailoverTarget(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("target_group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TargetGroupID))
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteByte(')')
	return builder.String()
}

// APIKeyRouteFailoverTargets is a parsable slice of APIKeyRouteFailoverTarget.
type APIKeyRouteFailoverTargets []*APIKeyRouteFailoverTarget
