// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikeyroutefailovertarget"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// APIKeyRouteFailoverTargetDelete is the builder for deleting a APIKeyRouteFailoverTarget entity.
type APIKeyRouteFailoverTargetDelete struct {
	config
	hooks    []Hook
	mutation *APIKeyRouteFailoverTargetMutation
}

// Where appends a list predicates to the APIKeyRouteFailoverTargetDelete builder.
func (_d *APIKeyRouteFailoverTargetDelete) Where(ps ...predicate.APIKeyRouteFailoverTarget) *APIKeyRouteFailoverTargetDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *APIKeyRouteFailoverTargetDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *APIKeyRouteFailoverTargetDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *APIKeyRouteFailoverTargetDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(apikeyroutefailovertarget.Table, sqlgraph.NewFieldSpec(apikeyroutefailovertarget.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// APIKeyRouteFailoverTargetDeleteOne is the builder for deleting a single APIKeyRouteFailoverTarget entity.
type APIKeyRouteFailoverTargetDeleteOne struct {
	_d *APIKeyRouteFailoverTargetDelete
}

// Where appends a list predicates to the APIKeyRouteFailoverTargetDelete builder.
func (_d *APIKeyRouteFailoverTargetDeleteOne) Where(ps ...predicate.APIKeyRouteFailoverTarget) *APIKeyRouteFailoverTargetDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *APIKeyRouteFailoverTargetDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{apikeyroutefailovertarget.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *APIKeyRouteFailoverTargetDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
