// Code generated by ent, DO NOT EDIT.

package apikeyroutefailovertarget

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldEQ(FieldUpdatedAt, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldEQ(FieldAPIKeyID, v))
}

// TargetGroupID applies equality check predicate on the "target_group_id" field. It's identical to TargetGroupIDEQ.
func TargetGroupID(v int64) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldEQ(FieldTargetGroupID, v))
}

// Priority applies equality check predicate on the "priority" field. It's identical to PriorityEQ.
func Priority(v int) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldEQ(FieldPriority, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldLTE(FieldUpdatedAt, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// TargetGroupIDEQ applies the EQ predicate on the "target_group_id" field.
func TargetGroupIDEQ(v int64) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldEQ(FieldTargetGroupID, v))
}

// TargetGroupIDNEQ applies the NEQ predicate on the "target_group_id" field.
func TargetGroupIDNEQ(v int64) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldNEQ(FieldTargetGroupID, v))
}

// TargetGroupIDIn applies the In predicate on the "target_group_id" field.
func TargetGroupIDIn(vs ...int64) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldIn(FieldTargetGroupID, vs...))
}

// TargetGroupIDNotIn applies the NotIn predicate on the "target_group_id" field.
func TargetGroupIDNotIn(vs ...int64) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldNotIn(FieldTargetGroupID, vs...))
}

// PriorityEQ applies the EQ predicate on the "priority" field.
func PriorityEQ(v int) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldEQ(FieldPriority, v))
}

// PriorityNEQ applies the NEQ predicate on the "priority" field.
func PriorityNEQ(v int) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldNEQ(FieldPriority, v))
}

// PriorityIn applies the In predicate on the "priority" field.
func PriorityIn(vs ...int) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldIn(FieldPriority, vs...))
}

// PriorityNotIn applies the NotIn predicate on the "priority" field.
func PriorityNotIn(vs ...int) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldNotIn(FieldPriority, vs...))
}

// PriorityGT applies the GT predicate on the "priority" field.
func PriorityGT(v int) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldGT(FieldPriority, v))
}

// PriorityGTE applies the GTE predicate on the "priority" field.
func PriorityGTE(v int) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldGTE(FieldPriority, v))
}

// PriorityLT applies the LT predicate on the "priority" field.
func PriorityLT(v int) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldLT(FieldPriority, v))
}

// PriorityLTE applies the LTE predicate on the "priority" field.
func PriorityLTE(v int) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.FieldLTE(FieldPriority, v))
}

// HasAPIKey applies the HasEdge predicate on the "api_key" edge.
func HasAPIKey() predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, APIKeyTable, APIKeyColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeyWith applies the HasEdge predicate on the "api_key" edge with a given conditions (other predicates).
func HasAPIKeyWith(preds ...predicate.APIKey) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(func(s *sql.Selector) {
		step := newAPIKeyStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTargetGroup applies the HasEdge predicate on the "target_group" edge.
func HasTargetGroup() predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TargetGroupTable, TargetGroupColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTargetGroupWith applies the HasEdge predicate on the "target_group" edge with a given conditions (other predicates).
func HasTargetGroupWith(preds ...predicate.Group) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(func(s *sql.Selector) {
		step := newTargetGroupStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.APIKeyRouteFailoverTarget) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.APIKeyRouteFailoverTarget) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.APIKeyRouteFailoverTarget) predicate.APIKeyRouteFailoverTarget {
	return predicate.APIKeyRouteFailoverTarget(sql.NotPredicates(p))
}
